# Generated by Django 3.0.8 on 2020-07-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
    ]
