# Generated by Django 3.0.8 on 2020-07-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_keyresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('created_at',)},
        ),
    ]
